#!/bin/bash

source environment || exit 1

# check for FIXME
output=`grep -RlI "FIXME" . 2> /dev/null`
if [ -n "$output" ]
then
	echo "There are FIXMEs in the code."
	exit 2
fi

# compile everything
build_directories=(
	"."
)

for d in ${build_directories[*]}
do
	echo "-------------------- BUILDING $d --------------------"
	make -C "$d" || exit 3
done

# run basic analysis
ds="fill7291/Totem1"
./run -no-bckg "distill.cc" "data/$ds"

# make comparison to reference
# TODO
