#!/bin/bash

# get input
reference_directory="$1"
if [ -z "$reference_directory" ]
then
	reference_directory=`ls -d ../IB/4rp/*/|head -n 1`
	echo "* sitting default reference directory: $reference_directory"
fi

log_short="$2"
if [ -z "$log_short" ]
then
	log_short="test.log_short"
fi

# reset
rm -f "$log_short"

echo "* starting test at: $(pwd -P)" >> "$log_short"

# prepare environment
source environment || exit 1

# check for FIXME
output=`grep -RlI "FIXME" . 2> /dev/null  | grep -v .git | grep -v test/run_test`
if [ -n "$output" ]
then
	echo "There are FIXMEs in the code."
	exit 2
fi

echo "* FIXME check OK" >> "$log_short"

# check for TODO
n_TODO=`grep -RlI "TODO" . 2> /dev/null  | grep -v .git | grep -v test/run_test|wc -l`

if [ "$n_TODO" -eq "0" ]
then
	echo "* TODO check OK" >> "$log_short"
else
	echo "* TODO check: $n_TODO" files affected >> "$log_short"
fi

# compile everything
for mkf in `find . -name *makefile|grep -v OLD`
do
	dir=${mkf%/makefile}

	echo "-------------------- BUILDING $dir --------------------"
	make -C "$dir" -j8 || exit 3
done

echo "* compilation OK" >> "$log_short"

# TODO: add static analysis check

# run basic analysis
echo "-------------------- RUNNING ANALYSIS --------------------"
ds="fill7291/Totem1"

./run -no-bckg "distill.cc" "data/$ds" || exit 10
./run -no-bckg "distill.cc" "data/$ds" -danti || exit 11

./run -no-bckg "distributions.cc" "data/$ds" -O "-bootstrap 1 -details 5" || exit 12

./run -no-bckg "resolution_fit.cc" "data/$ds" || exit 13

# TODO: uncomment once the RP directory is restored
#./run -no-bckg "process_timber.cc" "data/$ds" || exit 20

./run -no-bckg "alignment.cc" "data/$ds" || exit 21
./run -no-bckg "alignment_fit.cc" "data/$ds" || exit 22

./run -no-bckg "eff3outof4.cc" "data/$ds" || exit 23
./run -no-bckg "eff3outof4_details.cc" "data/$ds" || exit 24
./run -no-bckg "eff3outof4_fit.cc" "data/$ds" || exit 25

./run -no-bckg "pileup.cc" "data/$ds" || exit 26

#./run -no-bckg "unfolding_cf_mc.cc" "data/$ds" || exit 27
./run -no-bckg "unfolding_cf_ni.cc" "data/$ds" || exit 28

./run -no-bckg "distributions_anti.cc" "data/$ds" -danti || exit 29

./run -no-bckg "distributions.cc" "data/$ds" || exit 30

./run -no-bckg "alignment_final.cc" "data/$ds" || exit 31

# TODO: merge || exit 40

echo "* analysis check OK" >> "$log_short"

# make comparison to reference
echo "-------------------- RUNNING COMPARISON --------------------"

n_diff="0"

function MakeOneComparison()
{
	local file="$1"
	local obj="$2"

	test/compare \
		"./data/$ds/$file" "$obj" \
		"$reference_directory/data/$ds/$file" "$obj" || let n_diff+=1
}

if [ "$reference_directory" == "none" ]
then
	echo "* comparison not run (missing reference)" >> "$log_short"
else
	MakeOneComparison "distributions_45b_56t.root" "acceptance correction/eb/h_t_after"
	MakeOneComparison "distributions_45t_56b.root" "acceptance correction/eb/h_t_after"

	MakeOneComparison "distributions_anti_45b_56b.root" "acceptance correction/eb/h_t_after"
	MakeOneComparison "distributions_anti_45t_56t.root" "acceptance correction/eb/h_t_after"

	if [ "$n_diff" -eq "0" ]
	then
		echo "* comparison OK" >> "$log_short"
	else
		echo "* comparison: $_diff differences" >> "$log_short"
	fi
fi