#!/bin/bash

# get input
reference_directory="$1"
if [ -z "$reference_directory" ]
then
	reference_directory="none"
fi

log_short="$2"
if [ -z "$log_short" ]
then
	log_short="test.log_short"
fi

# reset
rm -f "$log_short"

echo "* starting test at: " >> "$log_short"

# prepare environment
source environment || exit 1

# check for FIXME
output=`grep -RlI "FIXME" . 2> /dev/null  | grep -v .git | grep -v test/run_test`
if [ -n "$output" ]
then
	echo "There are FIXMEs in the code."
	exit 2
fi

echo "* FIXME check OK" >> "$log_short"

# compile everything
for mkf in `find . -name *makefile|grep -v OLD`
do
	dir=${mkf%/makefile}

	echo "-------------------- BUILDING $dir --------------------"
	make -C "$dir" -j8 || exit 3
done

echo "* compilation OK" >> "$log_short"

# TODO: add static analysis check

# run basic analysis
echo "-------------------- RUNNING ANALYSIS --------------------"
ds="fill7291/Totem1"
./run -no-bckg "distill.cc" "data/$ds" || exit 10
./run -no-bckg "distill.cc" "data/$ds" -danti || exit 11

./run -no-bckg "distributions.cc" "data/$ds" -O "-bootstrap 1 -details 5" || exit 12

./run -no-bckg "resolution_fit.cc" "data/$ds" || exit 13

# TODO: uncomment once the RP directory is restored
#./run -no-bckg "process_timber.cc" "data/$ds" || exit 20

./run -no-bckg "alignment.cc" "data/$ds" || exit 21
./run -no-bckg "alignment_fit.cc" "data/$ds" || exit 22

./run -no-bckg "eff3outof4.cc" "data/$ds" || exit 23
./run -no-bckg "eff3outof4_details.cc" "data/$ds" || exit 24
./run -no-bckg "eff3outof4_fit.cc" "data/$ds" || exit 25

./run -no-bckg "pileup.cc" "data/$ds" || exit 26

#./run -no-bckg "unfolding_cf_mc.cc" "data/$ds" || exit 27
./run -no-bckg "unfolding_cf_ni.cc" "data/$ds" || exit 28

./run -no-bckg "distributions_anti.cc" "data/$ds" -danti || exit 29

./run -no-bckg "distributions.cc" "data/$ds" || exit 30

./run -no-bckg "alignment_final.cc" "data/$ds" || exit 31

# TODO: merge || exit 40

echo "* analysis check OK" >> "$log_short"

# make comparison to reference
echo "-------------------- RUNNING COMPARISON --------------------"

if [ "$reference_directory" == "none" ]
then
	echo "* comparison not run (missing reference)" >> "$log_short"
else
	for dgn in 45b_56t 45t_56b
	do
		test/compare \
			"test/reference.root" "$dgn/acceptance correction/eb/h_t_after" \
			"data/fill7291/Totem1/distributions_$dgn.root" "acceptance correction/eb/h_t_after" || exit 50
	done

	echo "* comparison OK" >> "$log_short"
fi