#!/bin/bash

#----------------------------------------------------------------------------------------------------

function MakeFiles()
{
	dataset="$1"

	buffer=""
	for subdir in ${eos_subdirs[@]}
	do
		for file in `eos ls $eos_dir_base/$subdir|grep .root`
		do
			if [ -n "$buffer" ]
			then
				buffer="$buffer,\n"
			fi
			buffer="$buffer\t\t\"root://eostotem.cern.ch//$eos_dir_base/$subdir/$file\""
		done
	done

	local dir="../$dataset"
	mkdir -p "$dir"

	echo "* $dir"
	
	cat "input_files_template.h" | sed "\
			s|\$FILES|$buffer|;\
		" > "$dir/input_files.h"

	if [ ! -f "$dir/parameters.h" ]
	then
		cp "parameters_template.h" "$dir/parameters.h"
	fi
}

#----------------------------------------------------------------------------------------------------

eos_dir_base="/store/express/Run2018D/ExpressPhysics/FEVT/Express-v1/000/"

eos_subdirs=(
	"323/880/00000"
	"323/892/00000"
)
#MakeFiles "DS-test"

#----------

eos_subdirs=(
	"324/455/00000"
)
#MakeFiles "DS-fill7279"

#----------

eos_subdirs=(
	"324/458/00000"
	"324/460/00000"
)
#MakeFiles "DS-fill7280"

#----------

eos_subdirs=(
	"324/462/00000"
)
#MakeFiles "DS-fill7281"

#----------

eos_subdirs=(
	"324/463/00000"
	"324/464/00000"
	"324/465/00000"
)
#MakeFiles "DS-fill7282"

#----------

eos_subdirs=(
	"324/469/00000"
	"324/471/00000"
)
#MakeFiles "DS-fill7283"

#----------

eos_subdirs=(
	"324/485/00000"
)
#MakeFiles "DS-fill7284"

#----------

eos_subdirs=(
	"324/494/00000"
	"324/495/00000"
	"324/498/00000"
	"324/509/00000"
)
MakeFiles "DS-fill7285"

#----------

eos_subdirs=(
	"324/518/00000"
	"324/519/00000"
	"324/520/00000"
	"324/524/00000"
)
MakeFiles "DS-fill7286"

#----------

eos_subdirs=(
	"324/526/00000"
	"324/527/00000"
	"324/528/00000"
)
MakeFiles "DS-fill7287"

#----------

eos_subdirs=(
	"324/529/00000"
	"324/530/00000"
	"324/531/00000"
)
MakeFiles "DS-fill7288"

#----------

eos_subdirs=(
	"324/532/00000"
)
MakeFiles "DS-fill7289"

#----------

eos_subdirs=(
	"324/534/00000"
	"324/535/00000"
)
MakeFiles "DS-fill7290"

#----------

eos_subdirs=(
	"324/536/00000"
)
MakeFiles "DS-fill7291"

#----------

eos_subdirs=(
	"324/539/00000"
	"324/541/00000"
	"324/543/00000"
	"324/545/00000"
)
MakeFiles "DS-fill7292"
