#!/bin/bash

#----------------------------------------------------------------------------------------------------

function MakeFilesOne()
{
	subdir="$1"
	eos_dir="$2"
	run_sel="$3"

	echo "* $subdir"

	buffer=""
	for file in `eos ls $eos_dir|grep ${run_sel}|grep _reco_|grep .root`
	do
		if [ -n "$buffer" ]
		then
			buffer="$buffer,\n"
		fi
		buffer="$buffer\t\t\"root://eostotem.cern.ch//$eos_dir/$file\""

	done

	if [ "$buffer" == "" ]
	then
		return
	fi

	mkdir -p "$subdir"

	cat "input_files_template.h" | sed "\
			s|\$FILES|$buffer|;\
		" > "$subdir/input_files.h"

	if [ ! -f "$subdir/parameters.h" ]
	then
		echo "#include \"../parameters.h\"" > "$subdir/parameters.h"
	fi
}

#----------------------------------------------------------------------------------------------------

function MakeFiles()
{
	local fill="$1"
	local run_sel="$2"

	MakeFilesOne "../DS-fill${fill}/Totem1" "$eos_dir_base/Totem1/version3" "$run_sel"
	#MakeFilesOne "../DS-fill${fill}/EmptyBX" "$eos_dir_base/EmptyBX/version1" "$run_sel"
}

#----------------------------------------------------------------------------------------------------

eos_dir_base="/eos/totem/data/offline/2018/450GeV/beta100"

MakeFiles "7280" "324457\|324458\|324460"
MakeFiles "7281" "324461\|324462"
MakeFiles "7282" "324464\|324465"
MakeFiles "7283" "324467\|324469\|324471"
MakeFiles "7284" "324485"
MakeFiles "7285" "324498\|324509\|324513"
MakeFiles "7286" "324517\|324518\|324519\|324520\|324524"
MakeFiles "7287" "324526\|324527\|324528"
MakeFiles "7288" "324529\|324530\|324531"
MakeFiles "7289" "324532"
MakeFiles "7290" "324534\|324535"
MakeFiles "7291" "324536"
