#!/bin/bash

#----------------------------------------------------------------------------------------------------

function MakeFilesOne()
{
	local dir="$1"
	local eos_dir="$2"
	local run_sel="$3"

	echo "* $dir"

	# get list of input files
	local buffer=""
	for file in `eos ls $eos_dir|grep ${run_sel}|grep _reco_|grep .root`
	do
		if [ -n "$buffer" ]
		then
			buffer="$buffer,\n"
		fi
		buffer="$buffer  \"root://eostotem.cern.ch//$eos_dir/$file\""

	done

	if [ "$buffer" == "" ]
	then
		return
	fi

	# make list of files
	mkdir -p "$dir"

	(
		echo "import FWCore.ParameterSet.Config as cms"
		echo ""
		echo "input_files = cms.vstring("
		echo -e "$buffer"
		echo ")"
	) > "$dir/input_files.py"
}

#----------------------------------------------------------------------------------------------------

function MakeFiles()
{
	local fill="$1"
	local run_sel="$2"

	local dir="../data/fill${fill}"
	mkdir -p "$dir"

	# make stream-common config
	if [ ! -f "$dir/config_common.py" ]
	then
		(
			echo "import sys"
			echo "import os"
			echo "import FWCore.ParameterSet.Config as cms"
			echo ""
			echo "sys.path.append(os.path.relpath(\"../../../\"))"
			echo "from config_base import *"
		) > "$dir/config_common.py"
	fi

	# make per stream configs
	MakeFilesOne "$dir/Totem1" "$eos_dir_base/Totem1/version5" "$run_sel"
	MakeFilesOne "$dir/ZeroBias" "$eos_dir_base/ZeroBias/version5" "$run_sel"
	MakeFilesOne "$dir/EmptyBX" "$eos_dir_base/EmptyBX/version5" "$run_sel"
}

#----------------------------------------------------------------------------------------------------

eos_dir_base="/eos/totem/data/offline/2018/450GeV/beta100"

MakeFiles "7280" "324457\|324458\|324460"
MakeFiles "7281" "324461\|324462"
MakeFiles "7282" "324464\|324465"
MakeFiles "7283" "324467\|324469\|324471"
MakeFiles "7284" "324485"
MakeFiles "7285" "324498\|324509\|324513"
MakeFiles "7286" "324517\|324518\|324519\|324520\|324524"
MakeFiles "7287" "324526\|324527\|324528"
MakeFiles "7288" "324529\|324530\|324531"
MakeFiles "7289" "324532"
MakeFiles "7290" "324534\|324535"
MakeFiles "7291" "324536"
