#!/bin/bash

files_per_block="100"

#----------------------------------------------------------------------------------------------------

function FlushBuffer()
{
	local buffer="$1"
	local block_idx="$2"

	local dir="../$subdir/block${block_idx}"
	mkdir -p "$dir"

	echo "* $dir"
	
	cat "input_files_template.h" | sed "\
			s|\$FILES|$buffer|;\
			s|\$RUN|$run|;\
		" > "$dir/input_files.h"

	echo "#include \"../parameters.h\"" > "$dir/parameters.h"
}

#----------------------------------------------------------------------------------------------------

function MakeFiles()
{
	subdir="$1"
	run="$2"

	buffer=""
	buffer_size="0"

	block_idx="0"

	for dataset in ${datasets[*]}
	do
		for file in `das_client --query "file dataset=$dataset run=$run" --limit=0|grep store`
		do
			if [ -n "$buffer" ]
			then
				buffer="$buffer,\n"
				#buffer="$buffer\n"
			fi
			buffer="$buffer\t\t\"root://cmsxrootd.fnal.gov//$file\""
			#buffer="${buffer}root://cmsxrootd.fnal.gov//$file"

			let buffer_size+=1

			if [ "$buffer_size" -ge "$files_per_block" ]
			then
				FlushBuffer "$buffer" "$block_idx"
		
				buffer=""
				let buffer_size=0
				let block_idx+=1
			fi
		done
	done

	if [ "$buffer_size" -gt "0" ]
	then
		FlushBuffer "$buffer" "$block_idx"
	
		buffer=""
		let buffer_size=0
		let block_idx+=1
	fi
}

#----------------------------------------------------------------------------------------------------

datasets=(
	"/ZeroBias1/Run2018A-06Jun2018-v1/AOD"
	"/ZeroBias2/Run2018A-06Jun2018-v1/AOD"
	"/ZeroBias3/Run2018A-06Jun2018-v1/AOD"
	"/ZeroBias4/Run2018A-06Jun2018-v1/AOD"
	"/ZeroBias5/Run2018A-06Jun2018-v1/AOD"
	"/ZeroBias6/Run2018A-06Jun2018-v1/AOD"
	"/ZeroBias7/Run2018A-06Jun2018-v1/AOD"
	"/ZeroBias8/Run2018A-06Jun2018-v1/AOD"
	"/ZeroBias9/Run2018A-06Jun2018-v1/AOD"
	"/ZeroBias10/Run2018A-06Jun2018-v1/AOD"
)

MakeFiles "DS1_ZeroBias" "315922" &
MakeFiles "DS2_ZeroBias" "315934" &
MakeFiles "DS3_ZeroBias" "315956" &
