#!/bin/bash

base_dir="/afs/cern.ch/user/j/jkaspar/public/ForFrici/beta100/version_2021_02_22"

datasets=(
	"data/fill7280"
	"data/fill7281"
	"data/fill7282"
	"data/fill7283"
	"data/fill7284"
	"data/fill7285"
	"data/fill7289"
	"data/fill7291"
)

diagonals=(
	"45b_56t"
	"45t_56b"
)

for dataset in ${datasets[*]}
do
	dir="$base_dir/$dataset"
	mkdir -p "$dir"

	for diagonal in ${diagonals[*]}
	do
		cp "$dataset/Totem1/distributions_${diagonal}.root" "$dir/"
	done
done
