#!/bin/bash

base_dir="/afs/cern.ch/user/j/jkaspar/public/900GeV/beta100"

datasets=(
	"DS-fill7280"
	"DS-fill7281"
	"DS-fill7282"
	"DS-fill7283"
	"DS-fill7284"
	"DS-fill7285"
	"DS-fill7286"
	"DS-fill7287"
	"DS-fill7288"
	"DS-fill7289"
	"DS-fill7290"
	"DS-fill7291"
)

diagonals=(
	"45b_56t"
	"45t_56b"
)

for dataset in ${datasets[*]}
do
	dir="$base_dir/$dataset"
	mkdir -p "$dir"

	for diagonal in ${diagonals[*]}
	do
		cp "$dataset/Totem1/distributions_${diagonal}.root" "$dir/"
	done
done
