#!/bin/bash

#----------------------------------------------------------------------------------------------------
# cut combinations

cut_combinations=(
	""
	"1"

	"1,2"
	"1,2,5"
	"1,2,5,6"
	"1,2,5,6,7"
	"1,2,5,6,7,8"
	"1,2,5,6,7,8,9"
	"1,2,5,6,7,8,9,10"

	# cut 2 is used as a benchmarking distribution
	"1,5"
	"1,5,6"
	"1,5,6,7"
	"1,5,6,7,8"
	"1,5,6,7,8,9"
	"1,5,6,7,8,9,10"

	# cut 7 is used as a benchmarking distribution
	"1,2,5,6,8"
	"1,2,5,6,8,9"
	"1,2,5,6,8,9,10"

	# check distributions when a single cut is lifted
	"2,5,6,7,8,9,10"
	"1,2,6,7,8,9,10"
	"1,2,5,7,8,9,10"
	"1,2,5,6,7,9,10"
	"1,2,5,6,7,8,10"
	"1,2,5,6,7,8,9"
)

function RunCutCombinationReconstructions()
{
	for cut in "${cut_combinations[@]}"
	do
		tag="cuts:$cut"
		if [ "$cut" == "" ]
		then
			tag="no_cuts"
		fi
	
		echo "    $tag"
		mkdir -p "$tag"
	
		cd "$tag" || continue

		src_dir="$BASE_DIR/data/$dataset"
	
		for diagonal in "45b_56t" "45t_56b"
		do
			$BASE_DIR/.distributions -dgn "$diagonal" -details 0 -bootstrap 1 -input-dir "$src_dir" -cfg "$src_dir/config.py" -cuts "$cut" \
				&> "distributions_$diagonal.log" &
		done

		for diagonal in "45b_56b" "45t_56t"
		do
			$BASE_DIR/.distributions_anti -dgn "$diagonal" -details 0 -input-dir "$src_dir" -cfg "$src_dir/config.py" -cuts "$cut" \
				&> "distributions_anti_$diagonal.log" &
		done

		cd ".."
	done
}

#----------------------------------------------------------------------------------------------------
# n_si options

n_si_options=(
	2
	3
	4
	5
	6
)

function RunNSiReconstructions()
{
	for n_si in "${n_si_options[@]}"
	do
		tag="n_si=$n_si"

		echo "    $tag"
		mkdir -p "$tag"
	
		cd "$tag" || continue

		for diagonal in "45b_56t" "45t_56b"
		do
			$BASE_DIR/.distributions -dgn "$diagonal" -details 0 -bootstrap 1 -input-dir "$src_dir" -cfg "$src_dir/config.py" -n-si "$n_si" \
				&> "distributions_$diagonal.log" &
		done
	
		cd ".."
	done
}

#----------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------

make -C "../../" -j8 || exit 1

datasets=(
	# good quality
	"fill7280/Totem1"
	"fill7281/Totem1"
	"fill7282/Totem1"
	"fill7283/Totem1"
	"fill7284/Totem1"
	"fill7285/Totem1"
	"fill7289/Totem1"
	"fill7291/Totem1"

	# bad quality
	#"fill7286/Totem1"
	#"fill7287/Totem1"
	#"fill7288/Totem1"
	#"fill7290/Totem1"
)

cwd=`pwd -P`

for dataset in "${datasets[@]}"
do
	echo "* $dataset"

	mkdir -p "$dataset"
	cd "$dataset"

	RunCutCombinationReconstructions

	wait

	RunNSiReconstructions

	wait

	cd "$cwd"
done
