#!/bin/bash

make -C ../.. -j8 || exit 1

#----------------------------------------------------------------------------------------------------

function RunOne
{
	local fill="$1"
	
	echo "* $fill"

	./normalisation -input "../../data/fill$fill/Totem1" -print-details 0 -print-python 1 >> "../../data/fill$fill/config_common.py"
}

#----------------------------------------------------------------------------------------------------

RunOne "7280"
RunOne "7281"
RunOne "7282"
RunOne "7283"
RunOne "7284"
RunOne "7285"
RunOne "7289"
RunOne "7291"
