#!/bin/bash

#----------------------------------------------------------------------------------------------------
# defaults

diagonals=(
	"45b_56t"
	"45t_56b"
)

configurations=(
	"fit_2/none"

	"fit_2/sh-thx"
	"fit_2/sh-thx-LRasym"

	"fit_2/sh-thy"
	"fit_2/sh-thy-LRasym"
	"fit_2/sh-thy-TBuncor"
	"fit_2/sh-thy-TBuncor-LRasym"

	"fit_2/tilt-thx-thy"
	"fit_2/tilt-thx-thy-LRasym"

	"fit_2/sc-thxy-mode1"
	"fit_2/sc-thxy-mode2"
	"fit_2/sc-thxy-mode3"
	"fit_2/sc-thxy-mode4"

	"fit_2/dx-sigma"
	"fit_2/dy-sigma"
	"fit_2/dx-non-gauss"
#	"fit_2/dx-mx-corr"
#	"fit_2/dy-my-corr"

	"fit_2/eff-mode1"
	"fit_2/eff-mode2"
	"fit_2/eff-mode3"

	"fit_2/beam-mom"

	"fit_2/mx-sigma"
	"fit_2/my-sigma"

	"fit_2/bckg"

	"fit_2/norm"

	"fit_3/none"
)

stat=""

wait_for_jobs="n"

#----------------------------------------------------------------------------------------------------
# parse command line

function PrintUsage()
{
	echo "USAGE: run_multiple_mc_simu [option] [option] ..."
	echo "OPTIONS:"
	echo "    -events <int>    number of events to simulate"
	echo "    -wait            wait for jobs run in background"
}

while [ "$1" != "" ]
do
	key="$1"

	case $key in
		-h|--help)
			PrintUsage
			exit 0
		;;

		-events)
			stat="$2"
			shift
		;;

		-wait)
			wait_for_jobs="y"
			shift
		;;

		*)
			echo "ERROR: unknown option '$key'."
			PrintUsage
			exit 1
		;;
	esac

	shift
done


#----------------------------------------------------------------------------------------------------
# consistency check

if [ "$stat" == "" ]
then
	echo "ERROR: statistics not defined. Use '-events' option."
	PrintUsage
	exit 2
fi

#----------------------------------------------------------------------------------------------------

function ExecuteOne()
{
	echo "* $dir/$scenario"

	local cwd=`pwd -P`

	local tag="$scenario"

	local job_dir="$cwd"
	local job_file="$dir/.${tag}.job"
	local job_log_file="$dir/.${tag}.log_job"

	local command="{ time ./mc_simu -model \"$model\" -dgn \"$diagonal\" -scenario \"$scenario\" -events \"$stat\" -output \"$dir/$scenario.root\" ; } \&> \"$dir/$scenario.log\""

	cat "job_template" | sed "\
			s|\$CMSSW_BASE|$CMSSW_BASE|; \
			s|\$JOB_DIR|$job_dir|; \
			s|\$JOB_LOG_FILE|$job_log_file|; \
			s|\$COMMAND|$command|; \
		" > "$job_file"
	chmod u+x "$job_file"

	"./$job_file" &
}

#----------------------------------------------------------------------------------------------------

make -C ../../ -j8 || exit 1

for diagonal in ${diagonals[*]}
do
	for configuration in ${configurations[*]}
	do
		model=${configuration%%/*}
		scenario=${configuration##*/}

		dir="data-mc/$stat/$diagonal/$model"
		mkdir -p "$dir"

		ExecuteOne
	done
done

#----------------------------------------------------------------------------------------------------

if [ "$wait_for_jobs" == "y" ]
then
	wait
fi
